### ISSUE TITLE
Release is missing the leetcode.apkg file content

### ISSUE THREAD

**Issue by dropsonic** [prius/leetcode-anki#35]
When a new release is created via GitHub actions, the `leetcode.apkg` file is visible in the assets and has a size, but its content is missing (GitHub returns 404 when you try to download it).

An example: https://github.com/prius/leetcode-anki/releases/tag/refs%2Fheads%2Fmaster-1635295155

I tried to fork the repo and create a new release myself but ended up with the same issue: https://github.com/dropsonic/leetcode-anki/releases/tag/refs%2Fheads%2Fmaster-1676754546

The `Build Anki deck` workflow doesn't show any errors. The "Upload release asset" step succeeded without any errors.

**Comment by prius** [comment]
Hi @dropsonic,

Those releases are very outdated and unlikely they were containing a correct information anyway.

As a workaround I would suggest you to follow the instructions from the README file and generate the file yourself. I just tried it, the script still works and it takes 2 minutes to set up and run.

I also not sure I want to fix releases, because they contain a scrapped leectcode question and I'm not sure I can legally publish this information without their permission.

**Comment by dropsonic** [comment]
Sounds reasonable, thank you for your answer and for working on this project!
